# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0d22dfd2591781212a6dfd69b92d7e8aa380dfb8b3e86698b02f44e78bf577a17559c5f10c27a070e199b2892d54a63d02be4bb287fba2d4775e979cd97e87b8

test:
  secret_key_base: 378546321b1603a48a79e3a363b1dedfd764e090f98ff0109fc7179dcc93ad9641516e591836f27ce9f1466d8aea196f2c10d462f9565ee01ca99cf4596db10f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
